# Generated by Django 5.1.2 on 2025-02-17 02:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('event_type', models.CharField(max_length=255)),
                ('event_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('environment', models.CharField(max_length=255)),
                ('event_context', models.JSONField()),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed')], default='SCHEDULED', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
